### ISSUE TITLE
java.util.LinkedHashMap cannot be cast to org.springframework.social.gitlab.api.project.Project

### ISSUE THREAD

**Issue by obazoud** [burning-duck/spring-social-gitlab#11]
Since this [code](https://github.com/burning-duck/spring-social-gitlab/blob/develop/src/main/java/org/springframework/social/gitlab/api/core/impl/GitlabTemplate.java#L110), PagedList<T> does not return a `List<T>` with getContent but a `List<LinkedHashMap<?,?>>`.

For example, if after this [line](https://github.com/burning-duck/spring-social-gitlab/blob/develop/src/test/java/org/springframework/social/gitlab/api/project/impl/ProjectTest.java#L50), I add:

``` java
assertThat(projects.get(0).getId(), is(4L));
```

I get a _java.util.LinkedHashMap cannot be cast to org.springframework.social.gitlab.api.project.Project_.

**Comment by pbit** [comment]
Seems that Jackson has not enough type information to transform the response body into something usefull. So the fallback Map<String, Object> is used.
I will check what we can do here. The whole paging related code should be reviewed.

**Comment by pbit** [comment]
All tests are green.
Found solution on http://stackoverflow.com/questions/21987295/using-spring-resttemplate-in-generic-method-with-generic-parameter

**Comment by gminog** [comment]
@pbit I know this is a 2-year old post, but how exactly does the stackoverflow link resolve the issue?

According to the method signature of [org.springframework.data.domain.Slice.getContent()](http://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Slice.html#getContent--), a `List<T>` should be returned. Instead, all you get is a LinkedHashMap that obviously cannot be traversed properly. 

I have even tried a Reflection-based workaround, but to no avail since the depth of my `T` is just too much.
Any ideas @pbit @obazoud ?

**Comment by pbit** [comment]
hi @gminog Will try to revert my brain to 2015 ;)

We create a `ParameterizedTypeReference` to keep the information which is lost due to Javas  type erasure.
see [this helper method](https://github.com/burning-duck/spring-social-gitlab/blob/cf931ea53ec5c8e9beeeebb05669dd5ce6e86bd7/src/main/java/org/springframework/social/gitlab/api/core/impl/GitlabTemplate.java#L148)

> ... the depth of my T is just too much

You mean something like `List<Foo<Bar>>` ?
The solution found in this issue works for a single level of parameters e.g. `List<Foo>`.

Can you provide some code?

**Comment by gminog** [comment]
Thank you, I will check it and let you know! 

In the meantime, my Foo contains properties that are Lists of other classes that also contain Lists of other classes. Boy, that is endless!

**Comment by pbit** [comment]
This stuff is just needed for the top level Collection.
Nested types are handled by Jackson, which can be customized in multiple ways.

You could even try to create concrete classes for your Lists.
```
class FooList extends ArrayList<Foo> 
```

Closing this as its not related to this issue.
